basePath: /
definitions:
  request.Login:
    properties:
      captcha:
        description: 验证码
        type: string
      captchaId:
        description: 验证码ID
        type: string
      secret:
        description: '由用户名和密码组成，例如: {"username":"xxx","password":"xxxxxx"}'
        type: string
    required:
    - secret
    type: object
  request.ResetUserPassword:
    properties:
      id:
        description: id
        type: integer
      password:
        description: 密码，omitempty该字段为空时在序列化时忽略它
        type: string
    required:
    - id
    type: object
  response.Login:
    properties:
      token:
        description: 令牌
        type: string
      user:
        allOf:
        - $ref: '#/definitions/response.LoginUser'
        description: 用户信息
    type: object
  response.LoginGroups:
    properties:
      orgCode:
        description: 组织编码（唯一）
        type: string
      shortName:
        description: 组织简称
        type: string
      sort:
        description: 排序
        type: integer
      sysRoles:
        description: 组织下的用户绑定的角色
        items:
          $ref: '#/definitions/response.LoginRole'
        type: array
    type: object
  response.LoginRole:
    properties:
      roleCode:
        description: 角色编码（唯一）
        type: string
      roleName:
        description: 角色名
        type: string
      sort:
        description: 排序字段
        type: integer
    type: object
  response.LoginUser:
    properties:
      avatar:
        description: 头像
        type: string
      email:
        description: 邮箱
        type: string
      isAdmin:
        description: 是否管理员（每个组织的管理员）
        type: boolean
      logOperation:
        description: 是否记录操作记录
        type: boolean
      nickName:
        description: 昵称
        type: string
      phone:
        description: 手机号
        type: string
      sysGroups:
        description: 关联的组织
        items:
          $ref: '#/definitions/response.LoginGroups'
        type: array
      username:
        description: 用户名
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.SysCaptcha:
    properties:
      captchaId:
        description: 验证码id
        type: string
      captchaLength:
        description: 验证码长度
        type: integer
      openCaptcha:
        description: 是否开启验证码验证
        type: boolean
      picPath:
        description: 验证码图片
        type: string
    type: object
  response.SysDB:
    properties:
      newVersion:
        description: 新版本
        type: string
      oldVersion:
        description: 老版本
        type: string
      updated:
        description: 是否已更新
        type: boolean
    type: object
host: 127.0.0.1:8888
info:
  contact: {}
  description: 使用gin的全栈开发基础平台
  title: Oms-Admin Swagger API接口文档
  version: V1.0.0
paths:
  /base/captcha:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 返回验证码信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/response.SysCaptcha'
                msg:
                  type: string
              type: object
      summary: 获取验证码
      tags:
      - base
  /base/login:
    post:
      parameters:
      - description: secret（必填），验证码+验证码id（选填）
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: 返回用户信息,token
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/response.Login'
                msg:
                  type: string
              type: object
      summary: 用户登录
      tags:
      - base
  /cache/test-cache:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 测试local_cache
      tags:
      - test
  /init/check:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 返回提示信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 检查DB是否初始化
      tags:
      - db
  /init/db:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 返回提示信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 初始化DB
      tags:
      - db
  /update/check:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 返回提示信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/response.SysDB'
                msg:
                  type: string
              type: object
      summary: 检查更新
      tags:
      - db
  /update/db:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 返回提示信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/response.SysDB'
                msg:
                  type: string
              type: object
      summary: 升级DB
      tags:
      - db
  /user/disable/:{id}:
    delete:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 删除用户
      tags:
      - user
    put:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 禁用用户
      tags:
      - user
  /user/enable/:{id}:
    put:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 启用用户
      tags:
      - user
  /user/reset-pwd:
    put:
      parameters:
      - description: id（必填），password（必填）
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ResetUserPassword'
      produces:
      - application/json
      responses:
        "200":
          description: 返回加密的密码，前端自行解密
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 重置密码
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
  ApiKeyDomain:
    in: header
    name: x-group
    type: apiKey
swagger: "2.0"
