version: "3"

# 定义多个network，web和server通讯，server和mysql通讯，server和redis通讯，其他不能相互通讯
networks:
  api_network:
  db_network:
  cache_network:

# 设置mysql，redis持久化保存
volumes:
  mysql:
  redis:

services:
  web:
    build:
      context: ../../web
      dockerfile: ./Dockerfile
    container_name: oms-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      - api_network

  server:
    build:
      context: ../../server
      dockerfile: ./Dockerfile
    container_name: oms-server
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      - api_network
      - db_network
      - cache_network

  mysql:
    image: mysql:8.0.36
    container_name: oms-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'Mysql123Admin456'
      MYSQL_DATABASE: 'oms'
      MYSQL_USER: 'root'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db_network

  redis:
    image: redis:6.2.14
    container_name: oms-redis
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis:/data
    networks:
      - cache_network
